### ISSUE TITLE
Do not use "pure" MySQL function

### ISSUE THREAD

**Issue by RoyBellingan** [grapparubinsky/izwe#2]
https://github.com/grapparubinsky/izwe/blob/master/campagna.php#L11

$sql_res=mysqli_query($mysqli, "SELECT ...

You are not performing ANY error checking, and in case of error ... what went wrong ?
(also prefer to use the OOP sintax $mysqli->mysqli_query();

I think is very hard that someone intentionally perform a SQL inject, but... 
https://github.com/grapparubinsky/izwe/blob/master/ajax/tot.php#L27

Is veeery rough!

**Comment by grapparubinsky** [comment]
Hi Roy,
thank you for your interest in this project (or better, these "crude" few lines of code).

As of the commit name, this is a draft of the final code so error checking has not been performed.. tbh actually this page does nothing.

According to the use of this project the code will only run in a local webserver, so if the author of the sql injection is the same with root access level to code, database and machine.. I mean, it's fine with me :D
(same for https://github.com/grapparubinsky/izwe/issues/1 as long the computer is not connected to the internet at all but I agree this should be inserted into gitignore)
